### ISSUE TITLE
Traits Design Site Updates

### ISSUE THREAD

**Issue by Andresmaldonadonormelli** [ultra-sound-music/ultra-sound-music#55]
**TRAITS**
- Let's break up text into 3 different sections (find reference in Figma)
- Let's have the traits in "S1 Subhead" and Sassy color
- Badges (Debut, hometown, version) - Let's have them animate as hover over effect
- Labels to the traits bar (Sanity, Fame, Swagger, Energy, Texture, Space) : Let's have them in "Taffy" and move them 10px to the right.
- Trait bars -  let's flip them so that both bars starting point is  from the center and then animate out. 
- Let's add random values to the the trait bars. 
- Let's have them animate as user scrolls to that position, so that user can see the animation. 

- Audio bars..(will chat with Vijay about them)

<img width="716" alt="Screen Shot 2022-02-19 at 12 59 39 PM" src="https://user-images.githubusercontent.com/71088838/154813099-5b9e68fa-4da8-41a4-b2fa-5befa8faebe0.png">

-

**Comment by gxxcastillo** [comment]
> Let's break up text into 3 different sections
Done

> Let's have the traits in "S1 Subhead" and Sassy color
Done

> Badges (Debut, hometown, version) - Let's have them animate as hover over effect
I don't remember, but, I think we may have discussed this one. Animating on hover may give the impression that the badges are clickable. I'm going to animate them when they come into view, like the traits. See what you think.

> Labels to the traits bar (Sanity, Fame, Swagger, Energy, Texture, Space) : Let's have them in "Taffy" and move them 10px to the right.
Done

> Trait bars - let's flip them so that both bars starting point is from the center and then animate out.
Done

> Let's add random values to the the trait bars.
Done

> Let's have them animate as user scrolls to that position, so that user can see the animation.
Done. I added a little bit of a delay so that the animation is more likely to be see, see what you think.

> Audio bars..(will chat with Vijay about them)
Cool, I saw the options you posted - they look amazing.  Let me know if you would like to discuss or if you guys came to a conclusion on which to go with.
